services:
  blizzquiz-web:
    image: node:20-bullseye
    container_name: blizzquiz-web
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8088:3000"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development